### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by uk-ar** [uk-ar/CycleReactNativeEx#115]
- [ ] debug cell close
- [ ] enable linking
- [ ] debug data retrieve
- [ ] improve navigation
- [ ] enable webview for borrow
